export const gameTemplate = {
  name: "",
  single: [
    {
      category: "",
      clues: [
        {
          answer: "",
          media: "",
          question: "",
          value: 200,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 400,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 600,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 800,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 1000,
          double: false,
        },
      ],
    },
    {
      category: "",
      clues: [
        {
          answer: "",
          media: "",
          question: "",
          value: 200,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 400,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 600,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 800,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 1000,
          double: false,
        },
      ],
    },
    {
      category: "",
      clues: [
        {
          answer: "",
          media: "",
          question: "",
          value: 200,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 400,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 600,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 800,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 1000,
          double: false,
        },
      ],
    },
    {
      category: "",
      clues: [
        {
          answer: "",
          media: "",
          question: "",
          value: 200,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 400,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 600,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 800,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 1000,
          double: false,
        },
      ],
    },
    {
      category: "",
      clues: [
        {
          answer: "",
          media: "",
          question: "",
          value: 200,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 400,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 600,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 800,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 1000,
          double: false,
        },
      ],
    },
    {
      category: "",
      clues: [
        {
          answer: "",
          media: "",
          question: "",
          value: 200,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 400,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 600,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 800,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 1000,
          double: false,
        },
      ],
    },
  ],
  double: [
    {
      category: "",
      clues: [
        {
          answer: "",
          media: "",
          question: "",
          value: 400,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 800,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 1200,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 1600,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 2000,
          double: false,
        },
      ],
    },
    {
      category: "",
      clues: [
        {
          answer: "",
          media: "",
          question: "",
          value: 400,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 800,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 1200,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 1600,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 2000,
          double: false,
        },
      ],
    },
    {
      category: "",
      clues: [
        {
          answer: "",
          media: "",
          question: "",
          value: 400,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 800,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 1200,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 1600,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 2000,
          double: false,
        },
      ],
    },
    {
      category: "",
      clues: [
        {
          answer: "",
          media: "",
          question: "",
          value: 400,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 800,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 1200,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 1600,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 2000,
          double: false,
        },
      ],
    },
    {
      category: "",
      clues: [
        {
          answer: "",
          media: "",
          question: "",
          value: 400,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 800,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 1200,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 1600,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 2000,
          double: false,
        },
      ],
    },
    {
      category: "",
      clues: [
        {
          answer: "",
          media: "",
          question: "",
          value: 400,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 800,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 1200,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 1600,
          double: false,
        },
        {
          answer: "",
          media: "",
          question: "",
          value: 2000,
          double: false,
        },
      ],
    },
  ],
  final: {
    category: "",
    clue: {
      answer: "",
      media: "",
      question: "",
    },
  },
};
